import { Metadata } from "next";
import { DM_Sans } from "next/font/google";

import '../../app/globals.css';

import Footer from "@/components/organisms/Footer";
import Navbar from "@/components/organisms/NavBar";
import FAQAccordion from "@/components/organisms/faq";

const dmSans = DM_Sans({
  variable: "--font-dm-sans", // This links to your CSS variable
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={dmSans.variable}>
      <body className="antialiased bg-[#fef9ee]">
        <Navbar />
        {children}
        <FAQAccordion />
        <Footer />
      </body>
    </html>
  );
}
